# Sample Prometheus config
# This assumes that your Prometheus instance can access this application on localhost:8080

global:
  scrape_interval:     1s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 1s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'camel-app'
    scrape_interval: 1s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'app:8080' ]
  - job_name: 'grafana'
    scrape_interval: 1s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'grafana:3000' ]