apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.repository }}/{{ .Values.imageName }}:{{ .Values.version }}"
        imagePullPolicy: Always
        env:
        {{- range $key, $value := .Values.envVars }}
          - name: {{ $key }}
            value: {{ $value }}
        {{- end }}
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: {{ .Values.port }}
          initialDelaySeconds: {{ .Values.initialDelaySeconds }}
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: {{ .Values.port }}
          initialDelaySeconds: {{ .Values.initialDelaySeconds }}
          timeoutSeconds: 5